# Generated by Django 6.0.5 on 2026-05-12 21:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=80, verbose_name='Nomi (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='Nomi (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=80, verbose_name='Nomi (RU)')),
                ('icon', models.CharField(default='🍽️', max_length=10)),
            ],
            options={
                'verbose_name': 'Oshxona turi',
                'verbose_name_plural': 'Oshxona turlari',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('khiva', 'Xiva'), ('urgench', 'Urganch')], max_length=20)),
                ('price_range', models.CharField(choices=[('$', 'Arzon'), ('$$', "O'rtacha"), ('$$$', 'Qimmat'), ('$$$$', 'Premium')], default='$$', max_length=4)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting (0-5)')),
                ('address', models.CharField(max_length=300)),
                ('address_en', models.CharField(blank=True, max_length=300)),
                ('address_ru', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Ish vaqti')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('has_outdoor_seating', models.BooleanField(default=False, verbose_name='Tashqi joy')),
                ('is_halal', models.BooleanField(default=True, verbose_name='Halol')),
                ('is_vegetarian_friendly', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuisines', models.ManyToManyField(related_name='restaurants', to='restaurants.cuisine', verbose_name='Oshxona turlari')),
            ],
            options={
                'verbose_name': 'Restoran',
                'verbose_name_plural': 'Restoranlar',
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-is_cover', 'order'],
            },
        ),
    ]
