# Generated by Django 6.0.5 on 2026-05-13 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Sarlavha (UZ)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (RU)')),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('cover_image', models.ImageField(upload_to='events/', verbose_name='Asosiy rasm')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('location_uz', models.CharField(max_length=200, verbose_name='Manzil (UZ)')),
                ('location_en', models.CharField(blank=True, max_length=200, verbose_name='Manzil (EN)')),
                ('location_ru', models.CharField(blank=True, max_length=200, verbose_name='Manzil (RU)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True, verbose_name='Bepul')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Narx (UZS)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
