# Generated by Django 6.0.5 on 2026-05-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Sarlavha (UZ)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (RU)')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('excerpt_uz', models.TextField(max_length=300, verbose_name='Qisqa tavsif (UZ)')),
                ('excerpt_en', models.TextField(blank=True, max_length=300, verbose_name='Qisqa tavsif (EN)')),
                ('excerpt_ru', models.TextField(blank=True, max_length=300, verbose_name='Qisqa tavsif (RU)')),
                ('content_uz', models.TextField(verbose_name="To'liq matn (UZ)")),
                ('content_en', models.TextField(blank=True, verbose_name="To'liq matn (EN)")),
                ('content_ru', models.TextField(blank=True, verbose_name="To'liq matn (RU)")),
                ('cover_image', models.ImageField(upload_to='news/', verbose_name='Asosiy rasm')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Muallif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('published_at', models.DateTimeField(verbose_name='Chop etilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
