# Generated by Django 6.0.5 on 2026-05-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Emoji belgisi, masalan: 🏊', max_length=10)),
            ],
            options={
                'verbose_name': 'Qulaylik',
                'verbose_name_plural': 'Qulayliklar',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi?")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mehmonxona nomi')),
                ('city', models.CharField(choices=[('urgench', 'Urganch'), ('khiva', 'Xiva')], max_length=20, verbose_name='Shahar')),
                ('stars', models.IntegerField(verbose_name='Yulduzlar soni')),
                ('rating', models.FloatField(verbose_name='Reyting (0–10)')),
                ('price_per_night', models.IntegerField(verbose_name='Bir kechaga narx (UZS)')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('latitude', models.FloatField(verbose_name='Kenglik (lat)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (lng)')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google Maps havolasi')),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='hotels.amenity', verbose_name='Qulayliklar')),
            ],
            options={
                'verbose_name': 'Mehmonxona',
                'verbose_name_plural': 'Mehmonxonalar',
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/', verbose_name='Rasm')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Asosiy rasm?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='Mehmonxona')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['order'],
            },
        ),
    ]
