# Generated by Django 6.0.5 on 2026-05-13 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (UZ)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nomi (EN)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Nomi (RU)')),
                ('icon', models.CharField(help_text='Emoji belgisi, masalan: 🏊', max_length=10)),
            ],
            options={
                'verbose_name': 'Qulaylik',
                'verbose_name_plural': 'Qulayliklar',
                'ordering': ['name_uz'],
                'indexes': [models.Index(fields=['name_uz'], name='amenity_name_uz_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi?")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='contact_read_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi (asosiy)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)')),
                ('city', models.CharField(choices=[('urgench', 'Urganch'), ('khiva', 'Xiva')], max_length=20, verbose_name='Shahar')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Yulduzlar soni')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Reyting (0–10)')),
                ('price_per_night', models.PositiveIntegerField(verbose_name='Bir kechaga narx (UZS)')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='Manzil (EN)')),
                ('address_ru', models.CharField(blank=True, max_length=300, verbose_name='Manzil (RU)')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Kenglik (lat)')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Uzunlik (lng)')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google Maps havolasi')),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='hotels.amenity', verbose_name='Qulayliklar')),
            ],
            options={
                'verbose_name': 'Mehmonxona',
                'verbose_name_plural': 'Mehmonxonalar',
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/', verbose_name='Rasm')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Asosiy rasm?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='Mehmonxona')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city'], name='hotel_city_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_featured', '-rating'], name='hotel_featured_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['stars'], name='hotel_stars_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['price_per_night'], name='hotel_price_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelimage',
            index=models.Index(fields=['hotel', 'order'], name='hotel_image_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotelimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('hotel',), name='one_cover_image_per_hotel'),
        ),
    ]
