# Generated by Django 5.1.4 on 2026-05-25 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Kirish sanasi')),
                ('check_out', models.DateField(verbose_name='Chiqish sanasi')),
                ('guests', models.PositiveSmallIntegerField(default=1, verbose_name='Mehmonlar soni')),
                ('total_price', models.PositiveIntegerField(verbose_name='Umumiy narx (UZS)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Yakunlangan')], default='pending', max_length=20)),
                ('guest_name', models.CharField(max_length=200, verbose_name='Mehmon ismi')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.hotel', verbose_name='Mehmonxona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='booking_user_created_idx'), models.Index(fields=['hotel', 'check_in'], name='booking_hotel_checkin_idx'), models.Index(fields=['status'], name='booking_status_idx')],
            },
        ),
    ]
