# Generated by Django 6.0.5 on 2026-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil (EN)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil (RU)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nomi (asosiy)'),
        ),
    ]
