# Generated by Django 6.0.5 on 2026-05-12 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_address_en_hotel_address_ru_hotel_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Kenglik (lat)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Uzunlik (lng)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.PositiveIntegerField(verbose_name='Bir kechaga narx (UZS)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Reyting (0–10)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Yulduzlar soni'),
        ),
    ]
