# Generated by Django 6.0.5 on 2026-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_latitude_alter_hotel_longitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['name_uz'], name='amenity_name_uz_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', '-created_at'], name='contact_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city'], name='hotel_city_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_featured', '-rating'], name='hotel_featured_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['stars'], name='hotel_stars_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['price_per_night'], name='hotel_price_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelimage',
            index=models.Index(fields=['hotel', 'order'], name='hotel_image_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotelimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('hotel',), name='one_cover_image_per_hotel'),
        ),
    ]
