# Generated by Django 6.0.5 on 2026-05-12 21:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Sarlavha (UZ)')),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description_uz', models.TextField(max_length=300, verbose_name='Qisqa tavsif (UZ)')),
                ('short_description_en', models.TextField(blank=True, max_length=300)),
                ('short_description_ru', models.TextField(blank=True, max_length=300)),
                ('description_uz', models.TextField(verbose_name="To'liq tavsif (UZ)")),
                ('description_en', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('itinerary_uz', models.TextField(blank=True, verbose_name='Kun-bakun rejasi (UZ)')),
                ('itinerary_en', models.TextField(blank=True)),
                ('itinerary_ru', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='tours/', verbose_name='Asosiy rasm')),
                ('price', models.PositiveIntegerField(verbose_name='Narx (UZS)')),
                ('duration', models.PositiveIntegerField(verbose_name='Davomiyligi')),
                ('duration_type', models.CharField(choices=[('hours', 'Soat'), ('days', 'Kun')], default='hours', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=10)),
                ('max_people', models.PositiveIntegerField(default=20, verbose_name='Maks. kishi')),
                ('min_people', models.PositiveIntegerField(default=1, verbose_name='Min. kishi')),
                ('includes_uz', models.TextField(blank=True, verbose_name='Narxga kiradi (UZ)')),
                ('includes_en', models.TextField(blank=True)),
                ('includes_ru', models.TextField(blank=True)),
                ('excludes_uz', models.TextField(blank=True, verbose_name='Narxga kirmaydi (UZ)')),
                ('excludes_en', models.TextField(blank=True)),
                ('excludes_ru', models.TextField(blank=True)),
                ('meeting_point_uz', models.CharField(blank=True, max_length=200)),
                ('meeting_point_en', models.CharField(blank=True, max_length=200)),
                ('meeting_point_ru', models.CharField(blank=True, max_length=200)),
                ('guide_languages', models.CharField(default='Uzbek, English', max_length=100, verbose_name='Gid tillari')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
                'ordering': ['-is_featured', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
