# Generated by Django 6.0.5 on 2026-05-13 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Davlat')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting (1-5)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('comment', models.TextField(verbose_name='Fikr')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reviews_rev_content_627d80_idx'), models.Index(fields=['is_approved', '-created_at'], name='reviews_rev_is_appr_dbec64_idx')],
            },
        ),
    ]
