# Generated by Django 6.0.5 on 2026-05-13 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)')),
                ('icon', models.CharField(default='🏛️', max_length=10)),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('history_uz', models.TextField(blank=True, verbose_name='Tarix (UZ)')),
                ('history_en', models.TextField(blank=True, verbose_name='Tarix (EN)')),
                ('history_ru', models.TextField(blank=True, verbose_name='Tarix (RU)')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube)')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Kenglik (lat)')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Uzunlik (lng)')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Ish vaqti')),
                ('entrance_fee', models.PositiveIntegerField(default=0, verbose_name='Kirish narxi (UZS)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy joylarda chiqsin?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Diqqatga sazovor joy',
                'verbose_name_plural': 'Diqqatga sazovor joylar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attractions/', verbose_name='Rasm')),
                ('caption_uz', models.CharField(blank=True, max_length=200, verbose_name='Izoh (UZ)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Izoh (EN)')),
                ('caption_ru', models.CharField(blank=True, max_length=200, verbose_name='Izoh (RU)')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('order', models.PositiveIntegerField(default=0)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attractions.attraction')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['-is_cover', 'order'],
            },
        ),
    ]
