# Generated by Django 6.0.5 on 2026-05-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)')),
                ('icon', models.CharField(default='🏛️', max_length=10)),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('latitude', models.FloatField(verbose_name='Kenglik (lat)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (lng)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy joylarda chiqsin?')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Diqqatga sazovor joy',
                'verbose_name_plural': 'Diqqatga sazovor joylar',
                'ordering': ['order'],
            },
        ),
    ]
