# Generated by Django 6.0.5 on 2026-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_alter_attraction_latitude_alter_attraction_longitude'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['is_featured', 'order'], name='attraction_featured_order_idx'),
        ),
    ]
