# Generated by Django 6.0.5 on 2026-05-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_attraction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attractions/', verbose_name='Rasm')),
                ('caption_uz', models.CharField(blank=True, max_length=200, verbose_name='Izoh (UZ)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Izoh (EN)')),
                ('caption_ru', models.CharField(blank=True, max_length=200, verbose_name='Izoh (RU)')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['-is_cover', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Diqqatga sazovor joy', 'verbose_name_plural': 'Diqqatga sazovor joylar'},
        ),
        migrations.RemoveIndex(
            model_name='attraction',
            name='attraction_featured_order_idx',
        ),
        migrations.AddField(
            model_name='attraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='entrance_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Kirish narxi (UZS)'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='history_en',
            field=models.TextField(blank=True, verbose_name='Tarix (EN)'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='history_ru',
            field=models.TextField(blank=True, verbose_name='Tarix (RU)'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='history_uz',
            field=models.TextField(blank=True, verbose_name='Tarix (UZ)'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL (YouTube)'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='attractionimage',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attractions.attraction'),
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='image',
        ),
    ]
