# Generated by Django 6.0.5 on 2026-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Kasb/lavozim')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Reyting (1-5)')),
                ('text_uz', models.TextField(verbose_name='Matn (UZ)')),
                ('text_en', models.TextField(blank=True, verbose_name='Matn (EN)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Matn (RU)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Asosiy ro'yxatda")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz sharhi',
                'verbose_name_plural': 'Mijoz sharhlari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
