# Generated by Django 6.0.5 on 2026-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_provider', models.CharField(choices=[('osm', 'OpenStreetMap (default, bepul)'), ('carto_voyager', 'CartoDB Voyager (chiroyli, bepul)'), ('carto_positron', 'CartoDB Positron (light, minimal)'), ('carto_dark', 'CartoDB Dark Matter (dark theme)'), ('stadia_alidade', 'Stadia Alidade Smooth (premium look)'), ('stadia_outdoors', 'Stadia Outdoors (terrain)'), ('stamen_toner', 'Stamen Toner (black/white)'), ('stamen_terrain', 'Stamen Terrain (relief)'), ('esri_satellite', "Esri World Imagery (sun'iy yo'ldosh)"), ('esri_streets', 'Esri World Street Map'), ('opentopo', 'OpenTopoMap (topografiya)')], default='carto_voyager', help_text='Saytdagi barcha xaritalar uchun ishlatiladigan provayder', max_length=30, verbose_name='Xarita provayderi')),
                ('map_dark_provider', models.CharField(choices=[('osm', 'OpenStreetMap (default, bepul)'), ('carto_voyager', 'CartoDB Voyager (chiroyli, bepul)'), ('carto_positron', 'CartoDB Positron (light, minimal)'), ('carto_dark', 'CartoDB Dark Matter (dark theme)'), ('stadia_alidade', 'Stadia Alidade Smooth (premium look)'), ('stadia_outdoors', 'Stadia Outdoors (terrain)'), ('stamen_toner', 'Stamen Toner (black/white)'), ('stamen_terrain', 'Stamen Terrain (relief)'), ('esri_satellite', "Esri World Imagery (sun'iy yo'ldosh)"), ('esri_streets', 'Esri World Street Map'), ('opentopo', 'OpenTopoMap (topografiya)')], default='carto_dark', help_text="Foydalanuvchi dark mode'da bo'lsa ishlatiladigan provayder", max_length=30, verbose_name='Dark mode xarita provayderi')),
                ('map_default_zoom', models.PositiveIntegerField(default=13, help_text="Xarita boshlang'ich zoom darajasi (1-18)", verbose_name='Default zoom')),
                ('site_name', models.CharField(default='Visit Khorezm', max_length=100)),
                ('site_tagline', models.CharField(blank=True, default='Travel & Tourism', max_length=200)),
                ('site_description', models.TextField(blank=True, default='Xorazm viloyati turizm portali')),
                ('contact_email', models.EmailField(default='info@visitkhorezm.uz', max_length=254)),
                ('contact_phone', models.CharField(default='+998 61 226 56 56', max_length=30)),
                ('contact_address', models.CharField(default='Xiva, Xorazm viloyati', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Sayt nazorat rejimida bo'lsa, foydalanuvchilarga xabar ko'rsatiladi")),
                ('maintenance_message', models.TextField(blank=True, default='Sayt vaqtinchalik ishga yaroqsiz. Iltimos keyinroq qaytib keling.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
