# Generated by Django 6.0.5 on 2026-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_dark_provider',
            field=models.CharField(choices=[('carto_voyager', 'CartoDB Voyager (default, chiroyli)'), ('carto_positron', 'CartoDB Positron (light, minimal)'), ('carto_dark', 'CartoDB Dark Matter (dark theme)'), ('stadia_alidade', 'Stadia Alidade Smooth (premium look)'), ('stadia_outdoors', 'Stadia Outdoors (terrain)'), ('stamen_toner', 'Stamen Toner (black/white)'), ('stamen_terrain', 'Stamen Terrain (relief)'), ('esri_satellite', "Esri World Imagery (sun'iy yo'ldosh)"), ('esri_streets', 'Esri World Street Map')], default='carto_dark', help_text="Foydalanuvchi dark mode'da bo'lsa ishlatiladigan provayder", max_length=30, verbose_name='Dark mode xarita provayderi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_provider',
            field=models.CharField(choices=[('carto_voyager', 'CartoDB Voyager (default, chiroyli)'), ('carto_positron', 'CartoDB Positron (light, minimal)'), ('carto_dark', 'CartoDB Dark Matter (dark theme)'), ('stadia_alidade', 'Stadia Alidade Smooth (premium look)'), ('stadia_outdoors', 'Stadia Outdoors (terrain)'), ('stamen_toner', 'Stamen Toner (black/white)'), ('stamen_terrain', 'Stamen Terrain (relief)'), ('esri_satellite', "Esri World Imagery (sun'iy yo'ldosh)"), ('esri_streets', 'Esri World Street Map')], default='carto_voyager', help_text='Saytdagi barcha xaritalar uchun ishlatiladigan provayder', max_length=30, verbose_name='Xarita provayderi'),
        ),
    ]
