# Generated by Django 6.0.5 on 2026-05-13 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('taxi', 'Taksi'), ('bus', 'Avtobus / Marshrutka'), ('train', 'Poyezd')], max_length=10, verbose_name='Transport turi')),
                ('icon', models.CharField(default='🚕', max_length=10)),
                ('from_location_uz', models.CharField(max_length=200, verbose_name='Qaerdan (UZ)')),
                ('from_location_en', models.CharField(blank=True, max_length=200, verbose_name='Qaerdan (EN)')),
                ('from_location_ru', models.CharField(blank=True, max_length=200, verbose_name='Qaerdan (RU)')),
                ('to_location_uz', models.CharField(max_length=200, verbose_name='Qayerga (UZ)')),
                ('to_location_en', models.CharField(blank=True, max_length=200, verbose_name='Qayerga (EN)')),
                ('to_location_ru', models.CharField(blank=True, max_length=200, verbose_name='Qayerga (RU)')),
                ('duration_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Min vaqt (daqiqa)')),
                ('duration_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max vaqt (daqiqa)')),
                ('price_min', models.PositiveIntegerField(verbose_name='Min narx (UZS)')),
                ('price_max', models.PositiveIntegerField(verbose_name='Max narx (UZS)')),
                ('badge_uz', models.CharField(blank=True, default='', max_length=50)),
                ('badge_en', models.CharField(blank=True, default='', max_length=50)),
                ('badge_ru', models.CharField(blank=True, default='', max_length=50)),
                ('badge_style', models.CharField(choices=[('recommended', 'Recommended'), ('budget', 'Budget'), ('comfort', 'Comfort')], default='recommended', max_length=20)),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Transport yo'nalishi",
                'verbose_name_plural': "Transport yo'nalishlari",
                'ordering': ['order'],
                'indexes': [models.Index(fields=['transport_type', 'order'], name='transport_type_order_idx')],
            },
        ),
    ]
