# Generated by Django 6.0.5 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportroute',
            name='transport_type',
            field=models.CharField(
                choices=[
                    ('taxi', 'Taksi'),
                    ('bus', 'Avtobus / Marshrutka'),
                    ('train', 'Poyezd'),
                ],
                max_length=10,
                verbose_name='Transport turi',
            ),
        ),
    ]
