# Generated by Django 6.0.5 on 2026-05-12 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_transportroute_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportroute',
            name='badge_style',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('budget', 'Budget'), ('comfort', 'Comfort')], default='recommended', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='duration_max',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max vaqt (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='duration_min',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Min vaqt (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='price_max',
            field=models.PositiveIntegerField(verbose_name='Max narx (UZS)'),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='price_min',
            field=models.PositiveIntegerField(verbose_name='Min narx (UZS)'),
        ),
    ]
