# Generated by Django 6.0.5 on 2026-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_transportroute_badge_style_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['transport_type', 'order'], name='transport_type_order_idx'),
        ),
    ]
